server:
  port: 9003

spring:
  application:
    name: nacos-sentinel-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: kly


management:
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.atguigu.springcloud.entities
