server:
  port: 9002
spring:
  application:
    name: cloudalibaba-provicer-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.145.130:1111
#        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
