server:
  port: 8802

spring:
  application:
    name: cloud-stream-rabbitmq-consumer

  rabbitmq:
    host: 192.168.145.130
    port: 5672
    username: admin
    password: 123
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: atguiguA  # 分组


eureka:
  instance:
    instance-id: receive-8802.com
    prefer-ip-address: true     # 访问的路径变为IP地址
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 30 # 如果现在超过了5秒的间隔（默认是90秒）
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka





