server:
  port: 8001


eureka:
  client:
#    是否注册进eureka注册中心
    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
#    服务组件名称
    instance-id: paymentHystrix8001
#    是否显示ip
    prefer-ip-address: true
spring:
  application:
    name: cloud-provider-hystrix-Service
